apiVersion: v1
kind: Service
metadata:
  name: voicescribe-api
  labels:
    app: voicescribe
    tier: backend
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: voicescribe
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: voicescribe-web
  labels:
    app: voicescribe
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: voicescribe
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: voicescribe-redis
  labels:
    app: voicescribe
    tier: cache
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: voicescribe
    tier: cache
---
apiVersion: v1
kind: Secret
metadata:
  name: voicescribe-secrets
type: Opaque
data:
  # You should replace this with your actual base64-encoded API key
  # echo -n "your-api-key" | base64
  groq-api-key: eW91ci1hcGkta2V5
